apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 3306
          name: db
        envFrom:
          - configMapRef:
              name: configmap-mysql